server:
  port: 3020

eureka:
  client:
    service-url:
      defaultZone: http://58.20.17.84:1111/eureka/

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aliyun:3306/xxpaydb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    initialSize: 5    # 初始化大小
    minIdle: 5        # 最小
    maxActive: 20     # 最大
    maxWait: 60000    # 获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true                    # 打开PSCache
    maxPoolPreparedStatementPerConnectionSize: 20   # 指定每个连接上PSCache的大小
    filters: stat,wall,log4j                        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

  rabbitmq:
    addresses: aliyun:5672
    username: guest
    password: guest
    dynamic: true

config:
  ali:
    notify_url: http://58.20.17.84:5555/api_cloud/api/xxpay/notify/pay/aliPayNotifyRes.htm
    return_url: http://www.xxpay.org
  wx:
    certRootPath: /home/sdwx/cert
    notifyUrl: http://58.20.17.84:5555/api_cloud/api/xxpay/notify/pay/wxPayNotifyRes.htm

logging:
  file: /datalog/xxpay/xxpay-web.log